### ISSUE TITLE
Make `ConfigManager` read configuration from multiple files

### ISSUE THREAD

**Issue by leandro-lucarella-frequenz** [frequenz-floss/frequenz-sdk-python#65]
### What's needed?

Right now the `ConfigManager` is reading the configuration only from one file, but we need a way to set local config defaults and local config overrides.

### Proposed solution

The following config files should be read, by order of precedence:

1. **Local config defaults** will work as per-site constants, something to override the defaults provided by the code itself.
2. **Cloud sync config** is the configuration file written by the the Cloud Sync service with values taken from the UI.
3. **Local config overrides** will work as an emergency override file, to be able to *lock* some configuration in case some particular installation doesn't want to allow configuring some stuff through the UI for safety or other reasons.

So for example:

1. Defines:
   ```toml
   config1 = 11
   config2 = 12
   config3 = 13
   ```
2. Defines:
   ```toml
   config1 = 21
   config4 = 24
   config5 = 25
   ```
3. Defines:
   ```toml
   config1 = 31
   config3 = 33
   config4 = 34
   ```

Then the resulting config should be:
* ```toml
  config1 = 31
  config2 = 12
  config3 = 33
  config4 = 34
  config5 = 25
  ```

If there are issues reading one of the files (for example I/O error or there are syntax errors in the file), an error should be logged and the config manager should proceed with reading the next file.
